adminUser: admin
adminPassword: admin

admin:
  existingSecret: grafana-admin

persistence:
  enabled: false

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.localhost

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus-server.observability.svc.cluster.local
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        jsonData:
          derivedFields:
            - name: trace_id
              matcherRegex: '\"trace_id\":\"([0-9a-f]{32})\"'
              datasourceUid: tempo
              url: "$${__value.raw}"
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3200
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-5m"
            spanEndTimeShift: "5m"
            customQuery: true
            query: '{job="loki.source.kubernetes.pods"} |= "$${__trace.traceId}"'
          serviceMap:
            datasourceUid: prometheus

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    searchNamespace: ALL
  datasources:
    enabled: false
