adminUser: admin
adminPassword: admin

admin:
  existingSecret: grafana-admin

persistence:
  enabled: false

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.localhost

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus-server.observability.svc.cluster.local
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    searchNamespace: ALL
  datasources:
    enabled: false
