apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-infinity-datasource
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  infinity-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Infinity
        type: yesoreyeram-infinity-datasource
        uid: infinity
        access: proxy
        isDefault: false
        editable: true
